version: '3'
services:
  app:
    container_name: web_api
    build: .
    ports: 
      - 8080:5000
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - webapi-mysql          
    networks:
      - webapi


  webapi-mysql:
    image: mysql:8.0.26
    container_name: db_mysql
    ports: 
      - 3308:3306
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - webapi
  
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin_container
  #   depends_on:
  #     - webapi-mysql
  #   environment:
  #     - PMA_HOST=webapi-mysql # Note the "fullstack-mysql". Must be the name of the what you used as the mysql service.
  #     - PMA_USER=${DB_USER}
  #     - PMA_PORT=${DB_PORT}
  #     - PMA_PASSWORD=${DB_PASSWORD}
  #   ports:
  #     - 9090:80
  #   restart: always
  #   networks:
  #     - webapi


volumes:
  api:
  database_mysql:                  

# Networks to be created to facilitate communication between containers
networks:
  webapi:
    driver: bridge
